### ISSUE TITLE
util not a module 

### ISSUE THREAD

**Issue by brigetellen** [pkeilbach/pylsci#7]
Hello, 

A lot of your pylsci codes rely on the util package, however, this package does not seem to exist anywhere, or at least it is not available on Windows. Is there an alternate package that can be used?

**Comment by pkeilbach** [comment]
Hi brigetellen,

thanks for your question, I'm happy you use pylsci!

I wrote the util module only for the `demo.ipynb` Jupyter notebook, where it does some prework, as well as image reading and showing. The `pylsci` package itself does not need nor contain that module.

Hope this helps, let me know if you have further questions!

**Comment by pkeilbach** [comment]
Ahh this you mean!

As from the README:

```sh
# for this example, it is assumed you have a custom helper module (here it is the util.py module)
# that is responsible for converting your raw laser speckle images to the NumPy arrays expected by PyLSCI
from util import convert_speckle_to_numpy
```

`pylsci` expects its input to be a 2D or 3D numpy array, so what I want to say here is that you may need to write a custom helper module to do that job for you, i.e. you somehow need to convert you LSCI data to numpy arrays.

If your sensor software already does that for you and you have your LSCI data already as numpy arrays, you are good to go, and can forget about the util module ;) 

Putting such jobs in a file called `util` (or module, as for Python) is just a common convention in programming.

But I could make that a bit more obvious, I created an issue for that, see #9

**Comment by brigetellen** [comment]
That makes sense! So, I think that means that if i have a given image and can convert it into a 2d numpy array of pixels rows and columns, I could use the rest of the LSCI code as given. 

Thanks so much for your help

**Comment by pkeilbach** [comment]
Exactly! Let me know if you have further questions!

**Comment by brigetellen** [comment]
Hi, I was hoping you could answer one more question if you don't mind. 
If you set nbh_s=5, what does this mean exactly? Does it mean that the kernel size is a 5x5 matrix over the central pixel? 

Thank you

**Comment by pkeilbach** [comment]
Hi,
exactly! `nbh_s` stands for "spatial neighborhood", and with `nbh_s=5`, the kernen size is 5x5.

**Comment by pkeilbach** [comment]
@brigetellen I'd be happy if you accept my answer on [stackoverflow](https://stackoverflow.com/questions/72218784/how-to-install-util-not-utils-module) 🙂
